-- ═══════════════════════════════════════════════════════════════════════
--  ZUKKO — og'zaki savollar seed'i (170 ta)
--
--  BU FAYL QO'LDA TAHRIR QILINMAYDI — u generator bilan yasaladi:
--      node supabase/mkseed.mjs
--  Manba: content/verbal.json
--
--  Hamma savol 'draft' holatida tushadi: foydalanuvchiga faqat xodim
--  ko'rib chiqib nashr etgandan keyin chiqadi (to'rt ko'z qoidasi).
--  Qayta ishga tushirish xavfsiz: faqat hech kim tegmagan va mazmuni
--  o'zgargan qoralama yangilanadi; qolganlariga (jurnalga ham) tegilmaydi.
--
--  Qo'llash: supabase/apply.sh (bitta tranzaksiyada).
-- ═══════════════════════════════════════════════════════════════════════

set standard_conforming_strings = on;

insert into public.verbal_items as v
  (key, kind, level, uz_prompt, uz_stimulus, uz_options, ru_prompt, ru_stimulus, ru_options, correct, explain_uz, explain_ru, state)
values
  ('v001',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qo''l : qo''lqop = oyoq : ?',
   array['paypoq', 'tizza', 'shlyapa', 'qadam']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Рука : перчатка = нога : ?',
   array['носок', 'колено', 'шляпа', 'шаг']::text[],
   0,
   'Qo''lqop qo''lga kiyiladi, paypoq esa oyoqqa kiyiladi.',
   'Перчатку надевают на руку, а носок — на ногу.',
   'draft'),
  ('v002',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qalam : yozmoq = qaychi : ?',
   array['qog''oz', 'o''tkir', 'qirqmoq', 'tikmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Карандаш : писать = ножницы : ?',
   array['бумага', 'острые', 'резать', 'шить']::text[],
   2,
   'Qalam bilan yoziladi, qaychi bilan qirqiladi: asbob va uning vazifasi.',
   'Карандашом пишут, ножницами режут: инструмент и его назначение.',
   'draft'),
  ('v003',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Katta : kichik = baland : ?',
   array['uzun', 'past', 'keng', 'yuqori']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Большой : маленький = высокий : ?',
   array['длинный', 'низкий', 'широкий', 'верхний']::text[],
   1,
   'Katta va kichik — ma''nosi qarama-qarshi so''zlar. Balandning qarama-qarshisi — past.',
   '«Большой» и «маленький» — противоположности. Противоположность слова «высокий» — «низкий».',
   'draft'),
  ('v004',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Baliq : suzmoq = qush : ?',
   array['qanot', 'osmon', 'don', 'uchmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Рыба : плавать = птица : ?',
   array['крыло', 'небо', 'зерно', 'летать']::text[],
   3,
   'Baliq suzib harakatlanadi, qush esa uchib: jonzot va uning harakatlanish usuli.',
   'Рыба передвигается вплавь, а птица — летая: существо и его способ передвижения.',
   'draft'),
  ('v005',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Sigir : buzoq = qo''y : ?',
   array['jun', 'echki', 'qo''ra', 'qo''zi']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Корова : телёнок = овца : ?',
   array['шерсть', 'коза', 'загон', 'ягнёнок']::text[],
   3,
   'Buzoq — sigirning bolasi, qo''zi — qo''yning bolasi.',
   'Телёнок — детёныш коровы, ягнёнок — детёныш овцы.',
   'draft'),
  ('v006',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Oshpaz : oshxona = o''qituvchi : ?',
   array['bo''r', 'sinfxona', 'o''quvchi', 'kitob']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Повар : кухня = учитель : ?',
   array['мел', 'класс', 'ученик', 'книга']::text[],
   1,
   'Oshpaz oshxonada ishlaydi, o''qituvchi esa sinfxonada: kasb egasi va uning ish joyi.',
   'Повар работает на кухне, а учитель — в классе: человек и место его работы.',
   'draft'),
  ('v007',
   'analogy',
   1,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Ko''z : ko''rmoq = quloq : ?',
   array['bosh', 'ovoz', 'eshitmoq', 'gapirmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Глаз : видеть = ухо : ?',
   array['голова', 'звук', 'слышать', 'говорить']::text[],
   2,
   'Ko''z bilan ko''ramiz, quloq bilan eshitamiz: a''zo va uning vazifasi.',
   'Глазами мы видим, ушами — слышим: орган и его назначение.',
   'draft'),
  ('v008',
   'odd',
   1,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sabzi', 'olma', 'nok', 'o''rik']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['морковь', 'яблоко', 'груша', 'абрикос']::text[],
   0,
   'Olma, nok va o''rik — mevalar, sabzi esa sabzavot.',
   'Яблоко, груша и абрикос — фрукты, а морковь — овощ.',
   'draft'),
  ('v009',
   'odd',
   1,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['chumchuq', 'it', 'mushuk', 'quyon']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['воробей', 'собака', 'кошка', 'кролик']::text[],
   0,
   'It, mushuk va quyon — to''rt oyoqli hayvonlar, chumchuq esa qush.',
   'Собака, кошка и кролик — четвероногие звери, а воробей — птица.',
   'draft'),
  ('v010',
   'odd',
   1,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['stol', 'stul', 'qoshiq', 'divan']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['стол', 'стул', 'ложка', 'диван']::text[],
   2,
   'Stol, stul va divan — mebel, qoshiq esa mebel emas.',
   'Стол, стул и диван — мебель, а ложка — нет.',
   'draft'),
  ('v011',
   'odd',
   1,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['qizil', 'katta', 'sariq', 'ko''k']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['красный', 'большой', 'жёлтый', 'синий']::text[],
   1,
   'Qizil, sariq va ko''k — ranglar, «katta» esa o''lchamni bildiradi.',
   'Красный, жёлтый и синий — цвета, а «большой» обозначает размер.',
   'draft'),
  ('v012',
   'category',
   1,
   'Qaysi so''z shu guruhga kiradi?',
   'Kaptar, qarg''a, chumchuq',
   array['baqa', 'mushuk', 'baliq', 'laylak']::text[],
   'Какое слово относится к этой группе?',
   'Голубь, ворона, воробей',
   array['лягушка', 'кошка', 'рыба', 'аист']::text[],
   3,
   'Guruhdagilar — qushlar. Variantlar ichida faqat laylak qush.',
   'В группе — птицы. Среди вариантов птица только аист.',
   'draft'),
  ('v013',
   'category',
   1,
   'Qaysi so''z shu guruhga kiradi?',
   'Poyezd, avtobus, samolyot',
   array['yo''l', 'haydovchi', 'bekat', 'kema']::text[],
   'Какое слово относится к этой группе?',
   'Поезд, автобус, самолёт',
   array['дорога', 'водитель', 'остановка', 'корабль']::text[],
   3,
   'Guruhdagilar — transport vositalari. Kema ham transport, qolganlari esa yo''q.',
   'В группе — виды транспорта. Корабль тоже транспорт, остальные — нет.',
   'draft'),
  ('v014',
   'category',
   1,
   'Qaysi so''z shu guruhga kiradi?',
   'Etik, tufli, shippak',
   array['shlyapa', 'krossovka', 'ko''ylak', 'qo''lqop']::text[],
   'Какое слово относится к этой группе?',
   'Сапоги, туфли, тапочки',
   array['шляпа', 'кроссовки', 'рубашка', 'перчатки']::text[],
   1,
   'Guruhdagilar — poyabzal. Krossovka ham poyabzal.',
   'В группе — обувь. Кроссовки тоже обувь.',
   'draft'),
  ('v015',
   'relation',
   1,
   'Bu ikki so''z qanday bog''langan?',
   'G''ildirak — velosiped',
   array['ma''nosi qarama-qarshi', 'ma''nosi yaqin', 'qism va butun', 'hayvon va uning bolasi']::text[],
   'Как связаны эти два слова?',
   'Колесо — велосипед',
   array['противоположные по смыслу', 'близкие по смыслу', 'часть и целое', 'животное и его детёныш']::text[],
   2,
   'G''ildirak — velosipedning bir qismi.',
   'Колесо — часть велосипеда.',
   'draft'),
  ('v016',
   'relation',
   1,
   'Bu ikki so''z qanday bog''langan?',
   'Kulmoq — yig''lamoq',
   array['ma''nosi qarama-qarshi', 'qism va butun', 'ma''nosi yaqin', 'narsa va uning rangi']::text[],
   'Как связаны эти два слова?',
   'Смеяться — плакать',
   array['противоположные по смыслу', 'часть и целое', 'близкие по смыслу', 'предмет и его цвет']::text[],
   0,
   'Kulmoq va yig''lamoq — ma''nosi qarama-qarshi so''zlar.',
   '«Смеяться» и «плакать» — слова с противоположным смыслом.',
   'draft'),
  ('v017',
   'relation',
   1,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Tugma — ko''ylak',
   array['Sahifa — kitob', 'Igna — ip', 'Ko''ylak — shim', 'Tikuvchi — ko''ylak']::text[],
   'В какой паре слова связаны так же?',
   'Пуговица — рубашка',
   array['Страница — книга', 'Иголка — нитка', 'Рубашка — брюки', 'Портной — рубашка']::text[],
   0,
   'Tugma — ko''ylakning qismi, sahifa — kitobning qismi.',
   'Пуговица — часть рубашки, страница — часть книги.',
   'draft'),
  ('v018',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Oshpaz : sho''rva = novvoy : ?',
   array['un', 'tandir', 'non', 'sotuvchi']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Повар : суп = пекарь : ?',
   array['мука', 'печь', 'хлеб', 'продавец']::text[],
   2,
   'Oshpaz sho''rva pishiradi, novvoy esa non yopadi: usta va u tayyorlaydigan narsa. Un — xomashyo.',
   'Повар варит суп, пекарь печёт хлеб: мастер и то, что он делает. Мука — это сырьё.',
   'draft'),
  ('v019',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'It : hurmoq = mushuk : ?',
   array['sichqon', 'miyovlamoq', 'sut', 'yugurmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Собака : лаять = кошка : ?',
   array['мышь', 'мяукать', 'молоко', 'бегать']::text[],
   1,
   'It huradi, mushuk esa miyovlaydi: hayvon va u chiqaradigan ovoz.',
   'Собака лает, кошка мяукает: животное и звук, который оно издаёт.',
   'draft'),
  ('v020',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Sovun : yuvmoq = sochiq : ?',
   array['hammom', 'yumshoq', 'taramoq', 'artmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Мыло : мыть = полотенце : ?',
   array['ванная', 'мягкое', 'причёсывать', 'вытирать']::text[],
   3,
   'Sovun bilan yuvinamiz, sochiq bilan artinamiz: narsa va uning vazifasi.',
   'Мылом моют, полотенцем вытирают: предмет и его назначение.',
   'draft'),
  ('v021',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Asal : asalari = sut : ?',
   array['qaymoq', 'oq', 'stakan', 'sigir']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Мёд : пчела = молоко : ?',
   array['сливки', 'белое', 'стакан', 'корова']::text[],
   3,
   'Asalni asalari beradi, sutni esa sigir: mahsulot va uni beradigan jonzot.',
   'Мёд даёт пчела, а молоко — корова: продукт и тот, кто его даёт.',
   'draft'),
  ('v022',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qor : oq = ko''mir : ?',
   array['issiq', 'qora', 'tosh', 'pech']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Снег : белый = уголь : ?',
   array['горячий', 'чёрный', 'камень', 'печь']::text[],
   1,
   'Qor oq rangda, ko''mir esa qora rangda: narsa va uning rangi.',
   'Снег белый, а уголь — чёрный: предмет и его цвет.',
   'draft'),
  ('v023',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Barmoq : qo''l = ekran : ?',
   array['rasm', 'yorug''', 'telefon', 'xabar']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Палец : рука = экран : ?',
   array['картинка', 'светлый', 'телефон', 'сообщение']::text[],
   2,
   'Barmoq qo''lning qismi, ekran esa telefonning qismi.',
   'Палец — часть руки, а экран — часть телефона.',
   'draft'),
  ('v024',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kunduz : tun = kirish : ?',
   array['chiqish', 'eshik', 'kechikish', 'boshlanish']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'День : ночь = вход : ?',
   array['выход', 'дверь', 'опоздание', 'начало']::text[],
   0,
   'Kunduz va tun — qarama-qarshi, kirish va chiqish ham qarama-qarshi.',
   'День и ночь противоположны, так же как вход и выход.',
   'draft'),
  ('v025',
   'analogy',
   2,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qalam : qog''oz = bo''r : ?',
   array['doska', 'o''qituvchi', 'oq', 'sinf']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Карандаш : бумага = мел : ?',
   array['доска', 'учитель', 'белый', 'класс']::text[],
   0,
   'Qalam bilan qog''ozga, bo''r bilan doskaga yoziladi: asbob va u bilan yoziladigan sirt.',
   'Карандашом пишут на бумаге, мелом — на доске: инструмент и поверхность для письма.',
   'draft'),
  ('v026',
   'odd',
   2,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['qoshiq', 'likopcha', 'bolg''a', 'piyola']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['ложка', 'тарелка', 'молоток', 'чашка']::text[],
   2,
   'Qoshiq, likopcha va piyola ovqatlanishda kerak, bolg''a esa asbob.',
   'Ложка, тарелка и чашка нужны за едой, а молоток — инструмент.',
   'draft'),
  ('v027',
   'odd',
   2,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['yomg''ir', 'quyosh', 'qor', 'do''l']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['дождь', 'солнце', 'снег', 'град']::text[],
   1,
   'Yomg''ir, qor va do''l bulutdan yog''adi, quyosh esa yog''maydi.',
   'Дождь, снег и град выпадают из облаков, а солнце — нет.',
   'draft'),
  ('v028',
   'odd',
   2,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['tulki', 'bo''ri', 'ayiq', 'tovuq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['лиса', 'волк', 'медведь', 'курица']::text[],
   3,
   'Tulki, bo''ri va ayiq — yovvoyi hayvonlar, tovuq esa uy parrandasi.',
   'Лиса, волк и медведь — дикие звери, а курица — домашняя птица.',
   'draft'),
  ('v029',
   'odd',
   2,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['yugurmoq', 'sakramoq', 'yurmoq', 'uxlamoq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['бегать', 'прыгать', 'ходить', 'спать']::text[],
   3,
   'Yugurmoq, sakramoq va yurmoq — harakat qilish, uxlamoq esa dam olish.',
   'Бегать, прыгать и ходить — движения, а спать — отдых.',
   'draft'),
  ('v030',
   'category',
   2,
   'Qaysi so''z shu guruhga kiradi?',
   'Bodring, pomidor, karam',
   array['olcha', 'kartoshka', 'uzum', 'yong''oq']::text[],
   'Какое слово относится к этой группе?',
   'Огурец, помидор, капуста',
   array['вишня', 'картофель', 'виноград', 'орех']::text[],
   1,
   'Guruhdagilar — sabzavotlar. Kartoshka ham sabzavot.',
   'В группе — овощи. Картофель тоже овощ.',
   'draft'),
  ('v031',
   'category',
   2,
   'Qaysi so''z shu guruhga kiradi?',
   'Gitara, skripka, arfa',
   array['qo''shiq', 'sahna', 'baraban', 'nota']::text[],
   'Какое слово относится к этой группе?',
   'Гитара, скрипка, арфа',
   array['песня', 'сцена', 'барабан', 'ноты']::text[],
   2,
   'Guruhdagilar — musiqa asboblari. Baraban ham musiqa asbobi.',
   'В группе — музыкальные инструменты. Барабан тоже музыкальный инструмент.',
   'draft'),
  ('v032',
   'category',
   2,
   'Qaysi so''z shu guruhga kiradi?',
   'Ko''ylak, shim, kurtka',
   array['sviter', 'tugma', 'shkaf', 'ip']::text[],
   'Какое слово относится к этой группе?',
   'Рубашка, брюки, куртка',
   array['свитер', 'пуговица', 'шкаф', 'нитка']::text[],
   0,
   'Guruhdagilar — kiyimlar. Sviter ham kiyim.',
   'В группе — одежда. Свитер тоже одежда.',
   'draft'),
  ('v033',
   'relation',
   2,
   'Bu ikki so''z qanday bog''langan?',
   'Tikuvchi — igna',
   array['usta va uning asbobi', 'qism va butun', 'ma''nosi yaqin', 'ma''nosi qarama-qarshi']::text[],
   'Как связаны эти два слова?',
   'Портной — иголка',
   array['мастер и его инструмент', 'часть и целое', 'близкие по смыслу', 'противоположные по смыслу']::text[],
   0,
   'Tikuvchi igna bilan ishlaydi — bu uning asbobi.',
   'Портной работает иголкой — это его инструмент.',
   'draft'),
  ('v034',
   'relation',
   2,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Qush — uya',
   array['Sigir — sut', 'Qush — qanot', 'Sigir — molxona', 'Tovuq — o''rdak']::text[],
   'В какой паре слова связаны так же?',
   'Птица — гнездо',
   array['Корова — молоко', 'Птица — крыло', 'Корова — коровник', 'Курица — утка']::text[],
   2,
   'Uya — qushning uyi, molxona — sigirning uyi: jonzot va u yashaydigan joy.',
   'Гнездо — жилище птицы, коровник — жилище коровы: животное и его жилище.',
   'draft'),
  ('v035',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kitob : qog''oz = ko''ylak : ?',
   array['tugma', 'mato', 'kiyim', 'tikuvchi']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Книга : бумага = рубашка : ?',
   array['пуговица', 'ткань', 'одежда', 'портной']::text[],
   1,
   'Kitob qog''ozdan, ko''ylak esa matodan qilinadi: narsa va uning materiali.',
   'Книгу делают из бумаги, а рубашку — из ткани: предмет и его материал.',
   'draft'),
  ('v036',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kalta : uzun = tor : ?',
   array['past', 'kichik', 'chuqur', 'keng']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Короткий : длинный = узкий : ?',
   array['низкий', 'маленький', 'глубокий', 'широкий']::text[],
   3,
   'Kalta — uzunning, tor — kengning qarama-qarshisi.',
   '«Короткий» противоположен «длинному», а «узкий» — «широкому».',
   'draft'),
  ('v037',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Bemor : shifokor = buzilgan mashina : ?',
   array['garaj', 'g''ildirak', 'haydovchi', 'usta']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Больной : врач = сломанная машина : ?',
   array['гараж', 'колесо', 'водитель', 'механик']::text[],
   3,
   'Bemorni shifokor davolaydi, buzilgan mashinani usta tuzatadi.',
   'Больного лечит врач, а сломанную машину чинит механик.',
   'draft'),
  ('v038',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Oyoq : yurmoq = tish : ?',
   array['og''iz', 'chaynamoq', 'oq', 'yutmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Ноги : ходить = зубы : ?',
   array['рот', 'жевать', 'белые', 'глотать']::text[],
   1,
   'Oyoq bilan yuramiz, tish bilan chaynaymiz. Yutish tish bilan emas, tomoq bilan bo''ladi.',
   'Ногами ходим, зубами жуём. Глотаем мы не зубами, а горлом.',
   'draft'),
  ('v039',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kutubxona : kitob = garaj : ?',
   array['eshik', 'haydovchi', 'mashina', 'benzin']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Библиотека : книги = гараж : ?',
   array['ворота', 'водитель', 'машина', 'бензин']::text[],
   2,
   'Kutubxonada kitoblar, garajda esa mashina saqlanadi: joy va u yerda saqlanadigan narsa.',
   'В библиотеке хранят книги, а в гараже — машину: место и то, что там хранят.',
   'draft'),
  ('v040',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Mix : bolg''a = vint : ?',
   array['otvyortka', 'taxta', 'temir', 'burmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Гвоздь : молоток = шуруп : ?',
   array['отвёртка', 'доска', 'железо', 'крутить']::text[],
   0,
   'Mix bolg''a bilan qoqiladi, vint esa otvyortka bilan buraladi: mahkamlagich va uning asbobi.',
   'Гвоздь забивают молотком, а шуруп закручивают отвёрткой: крепёж и инструмент для него.',
   'draft'),
  ('v041',
   'analogy',
   3,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Sichqon : mushuk = quyon : ?',
   array['tulki', 'sabzi', 'quloq', 'olmaxon']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Мышь : кошка = заяц : ?',
   array['лиса', 'морковь', 'уши', 'белка']::text[],
   0,
   'Mushuk sichqonni ovlaydi, tulki esa quyonni: o''lja va ovchi. Sabzini quyonning o''zi yeydi — munosabat teskari.',
   'Кошка охотится на мышь, лиса — на зайца: добыча и охотник. Морковь ест сам заяц — связь обратная.',
   'draft'),
  ('v042',
   'odd',
   3,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['dengiz', 'daryo', 'cho''l', 'ko''l']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['море', 'река', 'пустыня', 'озеро']::text[],
   2,
   'Dengiz, daryo va ko''l — suv havzalari, cho''l esa suvsiz joy.',
   'Море, река и озеро — водоёмы, а пустыня — место почти без воды.',
   'draft'),
  ('v043',
   'odd',
   3,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['qalam', 'o''chirg''ich', 'flomaster', 'bo''r']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['карандаш', 'ластик', 'фломастер', 'мел']::text[],
   1,
   'Qalam, flomaster va bo''r bilan yoziladi, o''chirg''ich esa yozuvni o''chiradi.',
   'Карандашом, фломастером и мелом пишут, а ластик стирает написанное.',
   'draft'),
  ('v044',
   'odd',
   3,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['kichik', 'mitti', 'mayda', 'ulkan']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['маленький', 'крошечный', 'мелкий', 'огромный']::text[],
   3,
   'Kichik, mitti va mayda — kichiklikni bildiradi, ulkan esa aksincha.',
   '«Маленький», «крошечный» и «мелкий» говорят о малом размере, а «огромный» — наоборот.',
   'draft'),
  ('v045',
   'odd',
   3,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sut', 'pishloq', 'qatiq', 'non']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['молоко', 'сыр', 'кефир', 'хлеб']::text[],
   3,
   'Sut, pishloq va qatiq — sut mahsulotlari, non esa bug''doy unidan pishiriladi.',
   'Молоко, сыр и кефир — молочные продукты, а хлеб пекут из муки.',
   'draft'),
  ('v046',
   'category',
   3,
   'Qaysi so''z shu guruhga kiradi?',
   'Mis, temir, oltin',
   array['rezina', 'kumush', 'shisha', 'tosh']::text[],
   'Какое слово относится к этой группе?',
   'Медь, железо, золото',
   array['резина', 'серебро', 'стекло', 'камень']::text[],
   1,
   'Guruhdagilar — metallar. Kumush ham metall.',
   'В группе — металлы. Серебро тоже металл.',
   'draft'),
  ('v047',
   'category',
   3,
   'Qaysi so''z shu guruhga kiradi?',
   'Tovuq, o''rdak, g''oz',
   array['bo''ri', 'ilon', 'kurka', 'toshbaqa']::text[],
   'Какое слово относится к этой группе?',
   'Курица, утка, гусь',
   array['волк', 'змея', 'индюк', 'черепаха']::text[],
   2,
   'Guruhdagilar — uy parrandalari. Kurka ham uy parrandasi.',
   'В группе — домашние птицы. Индюк тоже домашняя птица.',
   'draft'),
  ('v048',
   'category',
   3,
   'Qaysi so''z shu guruhga kiradi?',
   'Aprel, may, iyun',
   array['iyul', 'bahor', 'dushanba', 'soat']::text[],
   'Какое слово относится к этой группе?',
   'Апрель, май, июнь',
   array['июль', 'весна', 'понедельник', 'час']::text[],
   0,
   'Guruhdagilar — yil oylarining nomlari. Iyul ham yil oyi.',
   'В группе — названия месяцев. Июль тоже месяц.',
   'draft'),
  ('v049',
   'relation',
   3,
   'Bu ikki so''z qanday bog''langan?',
   'Mushuk — hayvon',
   array['biri ikkinchisining bir turi', 'qism va butun', 'ma''nosi qarama-qarshi', 'sabab va natija']::text[],
   'Как связаны эти два слова?',
   'Кошка — животное',
   array['первое — один из видов второго', 'часть и целое', 'противоположные по смыслу', 'причина и следствие']::text[],
   0,
   'Mushuk — hayvonlarning bir turi. U hayvonning bir qismi emas.',
   'Кошка — один из видов животных, а не часть животного.',
   'draft'),
  ('v050',
   'relation',
   3,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Uchuvchi — samolyot',
   array['Yo''lovchi — poyezd', 'Samolyot — aeroport', 'Haydovchi — avtobus', 'Qanot — samolyot']::text[],
   'В какой паре слова связаны так же?',
   'Лётчик — самолёт',
   array['Пассажир — поезд', 'Самолёт — аэропорт', 'Водитель — автобус', 'Крыло — самолёт']::text[],
   2,
   'Uchuvchi samolyotni, haydovchi avtobusni boshqaradi. Yo''lovchi esa faqat unda ketadi.',
   'Лётчик управляет самолётом, водитель — автобусом. Пассажир же только едет.',
   'draft'),
  ('v051',
   'relation',
   3,
   'Bu ikki so''z qanday bog''langan?',
   'Yomg''ir — ko''lmak',
   array['qism va butun', 'sabab va natija', 'ma''nosi yaqin', 'ma''nosi qarama-qarshi']::text[],
   'Как связаны эти два слова?',
   'Дождь — лужа',
   array['часть и целое', 'причина и следствие', 'близкие по смыслу', 'противоположные по смыслу']::text[],
   1,
   'Yomg''ir yog''gani uchun ko''lmak paydo bo''ladi.',
   'Лужа появляется из-за дождя.',
   'draft'),
  ('v052',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qo''shiqchi : qo''shiq = raqqos : ?',
   array['sahna', 'musiqa', 'kostyum', 'raqs']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Певец : песня = танцор : ?',
   array['сцена', 'музыка', 'костюм', 'танец']::text[],
   3,
   'Qo''shiqchi qo''shiq ijro etadi, raqqos esa raqs: ijrochi va uning ijrosi.',
   'Певец исполняет песню, танцор — танец: исполнитель и то, что он исполняет.',
   'draft'),
  ('v053',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Dushanba : seshanba = yanvar : ?',
   array['dekabr', 'qish', 'oy', 'fevral']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Понедельник : вторник = январь : ?',
   array['декабрь', 'зима', 'месяц', 'февраль']::text[],
   3,
   'Seshanba dushanbadan keyin keladi, fevral esa yanvardan keyin. Dekabr yanvardan oldin keladi.',
   'Вторник идёт после понедельника, февраль — после января. Декабрь идёт до января.',
   'draft'),
  ('v054',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Rassom : rasm = shoir : ?',
   array['qalam', 'she''r', 'kitobxon', 'so''z']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Художник : картина = поэт : ?',
   array['карандаш', 'стихотворение', 'читатель', 'слово']::text[],
   1,
   'Rassom rasm yaratadi, shoir esa she''r: ijodkor va uning asari.',
   'Художник создаёт картину, а поэт — стихотворение: автор и его произведение.',
   'draft'),
  ('v055',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Daqiqa : soat = santimetr : ?',
   array['uzunlik', 'millimetr', 'metr', 'gramm']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Минута : час = сантиметр : ?',
   array['длина', 'миллиметр', 'метр', 'грамм']::text[],
   2,
   'Daqiqa — soatning kichik bo''lagi, santimetr — metrning kichik bo''lagi. Millimetr esa santimetrdan ham kichik — yo''nalish teskari.',
   'Минута — малая доля часа, сантиметр — малая доля метра. Миллиметр меньше сантиметра — направление обратное.',
   'draft'),
  ('v056',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'G''isht : devor = so''z : ?',
   array['jumla', 'harf', 'qalam', 'ovoz']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Кирпич : стена = слово : ?',
   array['предложение', 'буква', 'карандаш', 'голос']::text[],
   0,
   'Devor g''ishtlardan, jumla esa so''zlardan tuziladi. Harf — so''zning o''zidan kichik bo''lak.',
   'Стена складывается из кирпичей, предложение — из слов. Буква меньше слова, это его часть.',
   'draft'),
  ('v057',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Ertaga : bugun = bugun : ?',
   array['kecha', 'ertaga', 'indinga', 'hozir']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Завтра : сегодня = сегодня : ?',
   array['вчера', 'завтра', 'послезавтра', 'сейчас']::text[],
   0,
   'Har safar bir kun orqaga: ertagadan bugunga, bugundan kechaga.',
   'Каждый раз на один день назад: от завтрашнего дня к сегодняшнему, от сегодняшнего — ко вчерашнему.',
   'draft'),
  ('v058',
   'analogy',
   4,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Uy : tom = quti : ?',
   array['karton', 'sovg''a', 'qopqoq', 'burchak']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Дом : крыша = коробка : ?',
   array['картон', 'подарок', 'крышка', 'угол']::text[],
   2,
   'Tom uyni ustidan yopadi, qopqoq esa qutini.',
   'Крыша закрывает дом сверху, а крышка — коробку.',
   'draft'),
  ('v059',
   'odd',
   4,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['quvnoq', 'g''amgin', 'xursand', 'shod']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['весёлый', 'грустный', 'радостный', 'счастливый']::text[],
   1,
   'Quvnoq, xursand va shod — yaxshi kayfiyatni bildiradi, g''amgin esa aksincha.',
   '«Весёлый», «радостный» и «счастливый» — о хорошем настроении, а «грустный» — наоборот.',
   'draft'),
  ('v060',
   'odd',
   4,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['santimetr', 'kilogramm', 'litr', 'termometr']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['сантиметр', 'килограмм', 'литр', 'термометр']::text[],
   3,
   'Santimetr, kilogramm va litr — o''lchov birliklari, termometr esa o''lchov asbobi.',
   'Сантиметр, килограмм и литр — единицы измерения, а термометр — измерительный прибор.',
   'draft'),
  ('v061',
   'odd',
   4,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['nonushta', 'tushlik', 'kechki ovqat', 'oshxona']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['завтрак', 'обед', 'ужин', 'кухня']::text[],
   3,
   'Nonushta, tushlik va kechki ovqat — ovqatlanish vaqtlari, oshxona esa xona.',
   'Завтрак, обед и ужин — приёмы пищи, а кухня — комната.',
   'draft'),
  ('v062',
   'odd',
   4,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['yostiq', 'sochiq', 'ko''rpa', 'choyshab']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['подушка', 'полотенце', 'одеяло', 'простыня']::text[],
   1,
   'Yostiq, ko''rpa va choyshab — yotoq anjomlari, sochiq esa artinish uchun.',
   'Подушка, одеяло и простыня — постельные принадлежности, а полотенцем вытираются.',
   'draft'),
  ('v063',
   'category',
   4,
   'Qaysi so''z shu guruhga kiradi?',
   'Qayin, terak, zarang',
   array['atirgul', 'o''rmon', 'eman', 'barg']::text[],
   'Какое слово относится к этой группе?',
   'Берёза, тополь, клён',
   array['роза', 'лес', 'дуб', 'лист']::text[],
   2,
   'Guruhdagilar — daraxtlar. Eman ham daraxt, atirgul esa buta.',
   'В группе — деревья. Дуб тоже дерево, а роза — кустарник.',
   'draft'),
  ('v064',
   'category',
   4,
   'Qaysi so''z shu guruhga kiradi?',
   'Uchburchak, to''rtburchak, beshburchak',
   array['oltiburchak', 'doira', 'kub', 'chiziq']::text[],
   'Какое слово относится к этой группе?',
   'Треугольник, четырёхугольник, пятиугольник',
   array['шестиугольник', 'круг', 'куб', 'линия']::text[],
   0,
   'Guruhdagilar — burchakli tekis shakllar (ko''pburchaklar). Oltiburchak ham shunday.',
   'В группе — плоские фигуры с углами (многоугольники). Шестиугольник тоже.',
   'draft'),
  ('v065',
   'category',
   4,
   'Qaysi so''z shu guruhga kiradi?',
   'Suv, sut, sharbat',
   array['choy', 'non', 'muz', 'shakar']::text[],
   'Какое слово относится к этой группе?',
   'Вода, молоко, сок',
   array['чай', 'хлеб', 'лёд', 'сахар']::text[],
   0,
   'Guruhdagilar — ichimliklar. Choy ham ichimlik.',
   'В группе — напитки. Чай тоже напиток.',
   'draft'),
  ('v066',
   'relation',
   4,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Urug'' — daraxt',
   array['Ildiz — daraxt', 'Bog''bon — daraxt', 'Tuxum — qush', 'Daraxt — o''rmon']::text[],
   'В какой паре слова связаны так же?',
   'Семя — дерево',
   array['Корень — дерево', 'Садовник — дерево', 'Яйцо — птица', 'Дерево — лес']::text[],
   2,
   'Urug''dan daraxt o''sib chiqadi, tuxumdan esa qush: boshlanish va undan rivojlanadigan jonzot.',
   'Из семени вырастает дерево, из яйца — птица: начало и то, что из него развивается.',
   'draft'),
  ('v067',
   'relation',
   4,
   'Bu ikki so''z qanday bog''langan?',
   'Katta — ulkan',
   array['ma''nosi qarama-qarshi', 'bir belgining kuchsiz va kuchli darajasi', 'qism va butun', 'sabab va natija']::text[],
   'Как связаны эти два слова?',
   'Большой — огромный',
   array['противоположные по смыслу', 'слабая и сильная степень одного признака', 'часть и целое', 'причина и следствие']::text[],
   1,
   'Ulkan — juda katta degani: belgi bir xil, faqat kuchliroq.',
   '«Огромный» значит «очень большой»: признак тот же, только сильнее.',
   'draft'),
  ('v068',
   'relation',
   4,
   'Bu ikki so''z qanday bog''langan?',
   'Termometr — harorat',
   array['qism va butun', 'ma''nosi qarama-qarshi', 'joy va u yerdagi narsa', 'asbob va u o''lchaydigan kattalik']::text[],
   'Как связаны эти два слова?',
   'Термометр — температура',
   array['часть и целое', 'противоположные по смыслу', 'место и то, что там находится', 'прибор и величина, которую он измеряет']::text[],
   3,
   'Termometr haroratni o''lchaydi.',
   'Термометр измеряет температуру.',
   'draft'),
  ('v069',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Bug'' : gaz = muz : ?',
   array['sovuq', 'suyuqlik', 'qor', 'qattiq jism']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Пар : газ = лёд : ?',
   array['холод', 'жидкость', 'снег', 'твёрдое тело']::text[],
   3,
   'Bug'' — suvning gaz holati, muz — suvning qattiq holati. Suyuq holat esa oddiy suvga mos keladi.',
   'Пар — газообразное состояние воды, лёд — твёрдое. Жидкое же состояние соответствует обычной воде.',
   'draft'),
  ('v070',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kompas : yo''nalish = soat : ?',
   array['strelka', 'vaqt', 'devor', 'raqam']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Компас : направление = часы : ?',
   array['стрелка', 'время', 'стена', 'цифра']::text[],
   1,
   'Kompas yo''nalishni, soat esa vaqtni ko''rsatadi: asbob va u ko''rsatadigan narsa. Strelka — asbobning qismi.',
   'Компас показывает направление, часы — время: прибор и то, что он показывает. Стрелка — лишь часть прибора.',
   'draft'),
  ('v071',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Shifokor : bemor = o''qituvchi : ?',
   array['maktab', 'dars', 'o''quvchi', 'bilim']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Врач : пациент = учитель : ?',
   array['школа', 'урок', 'ученик', 'знания']::text[],
   2,
   'Shifokor bemorga, o''qituvchi esa o''quvchiga yordam beradi: mutaxassis va u xizmat qiladigan odam.',
   'Врач помогает пациенту, учитель — ученику: специалист и человек, которому он помогает.',
   'draft'),
  ('v072',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Tikuvchi : mato = duradgor : ?',
   array['yog''och', 'arra', 'stol', 'ustaxona']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Портной : ткань = столяр : ?',
   array['древесина', 'пила', 'стол', 'мастерская']::text[],
   0,
   'Tikuvchi mato bilan, duradgor yog''och bilan ishlaydi: usta va uning materiali. Stol — mahsulot, arra — asbob.',
   'Портной работает с тканью, столяр — с древесиной: мастер и его материал. Стол — изделие, пила — инструмент.',
   'draft'),
  ('v073',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qanot : qush = suzgich : ?',
   array['baliq', 'suv', 'dum', 'qayiq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Крыло : птица = плавник : ?',
   array['рыба', 'вода', 'хвост', 'лодка']::text[],
   0,
   'Qanot — qushning, suzgich — baliqning harakatlanish a''zosi: qism va uning egasi.',
   'Крыло — орган движения птицы, плавник — рыбы: часть и её обладатель.',
   'draft'),
  ('v074',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Muzlatgich : sovuq = pech : ?',
   array['oshxona', 'non', 'issiqlik', 'temir']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Холодильник : холод = печь : ?',
   array['кухня', 'хлеб', 'тепло', 'железо']::text[],
   2,
   'Muzlatgich sovuq, pech esa issiqlik hosil qiladi.',
   'Холодильник создаёт холод, а печь — тепло.',
   'draft'),
  ('v075',
   'analogy',
   5,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Arra : taxta = qaychi : ?',
   array['tikuvchi', 'qog''oz', 'o''tkir', 'qirqmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Пила : доска = ножницы : ?',
   array['портной', 'бумага', 'острые', 'резать']::text[],
   1,
   'Arra taxtani, qaychi qog''ozni kesadi: asbob va u kesadigan material.',
   'Пила режет доску, ножницы — бумагу: инструмент и материал, который им режут.',
   'draft'),
  ('v076',
   'odd',
   5,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['chumoli', 'asalari', 'kapalak', 'o''rgimchak']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['муравей', 'пчела', 'бабочка', 'паук']::text[],
   3,
   'Chumoli, asalari va kapalak — hasharotlar (oltita oyoq). O''rgimchakning sakkizta oyog''i bor, u hasharot emas.',
   'Муравей, пчела и бабочка — насекомые (шесть ног). У паука восемь ног, он не насекомое.',
   'draft'),
  ('v077',
   'odd',
   5,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sher', 'yo''lbars', 'qoplon', 'bo''ri']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['лев', 'тигр', 'леопард', 'волк']::text[],
   3,
   'Sher, yo''lbars va qoplon — mushuksimonlar oilasidan, bo''ri esa itsimonlardan.',
   'Лев, тигр и леопард — из семейства кошачьих, а волк — из псовых.',
   'draft'),
  ('v078',
   'odd',
   5,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['roman', 'haykal', 'hikoya', 'ertak']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['роман', 'скульптура', 'рассказ', 'сказка']::text[],
   1,
   'Roman, hikoya va ertak — so''z bilan yaratilgan asarlar, haykal esa tosh yoki metalldan yasaladi.',
   'Роман, рассказ и сказка создаются словами, а скульптуру делают из камня или металла.',
   'draft'),
  ('v079',
   'odd',
   5,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['eshik', 'deraza', 'devor', 'darcha']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['дверь', 'окно', 'стена', 'форточка']::text[],
   2,
   'Eshik, deraza va darcha ochiladi va yopiladi, devor esa yo''q.',
   'Дверь, окно и форточка открываются и закрываются, а стена — нет.',
   'draft'),
  ('v080',
   'category',
   5,
   'Qaysi so''z shu guruhga kiradi?',
   'Kit, delfin, tyulen',
   array['morj', 'akula', 'sigir', 'qisqichbaqa']::text[],
   'Какое слово относится к этой группе?',
   'Кит, дельфин, тюлень',
   array['морж', 'акула', 'корова', 'краб']::text[],
   0,
   'Guruhdagilar — dengizda yashaydigan sutemizuvchilar. Morj ham shunday. Akula — baliq, sigir quruqlikda yashaydi.',
   'В группе — морские млекопитающие. Морж тоже. Акула — рыба, а корова живёт на суше.',
   'draft'),
  ('v081',
   'category',
   5,
   'Qaysi so''z shu guruhga kiradi?',
   'Shimol, janub, g''arb',
   array['sharq', 'chap', 'yuqori', 'xarita']::text[],
   'Какое слово относится к этой группе?',
   'Север, юг, запад',
   array['восток', 'лево', 'верх', 'карта']::text[],
   0,
   'Guruhdagilar — dunyo tomonlari. Sharq ham dunyo tomoni.',
   'В группе — стороны света. Восток тоже сторона света.',
   'draft'),
  ('v082',
   'category',
   5,
   'Qaysi so''z shu guruhga kiradi?',
   'Lupa, mikroskop, teleskop',
   array['tarozi', 'termometr', 'durbin', 'soat']::text[],
   'Какое слово относится к этой группе?',
   'Лупа, микроскоп, телескоп',
   array['весы', 'термометр', 'бинокль', 'часы']::text[],
   2,
   'Guruhdagilar narsalarni kattalashtirib ko''rsatadi. Durbin ham shunday.',
   'В группе — приборы, которые увеличивают изображение. Бинокль тоже.',
   'draft'),
  ('v083',
   'relation',
   5,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Qurg''oqchilik — hosilsizlik',
   array['Yomg''ir — bulut', 'Uyqusizlik — charchoq', 'Qish — yoz', 'Dehqon — dala']::text[],
   'В какой паре слова связаны так же?',
   'Засуха — неурожай',
   array['Дождь — туча', 'Бессонница — усталость', 'Зима — лето', 'Фермер — поле']::text[],
   1,
   'Qurg''oqchilik tufayli hosil bo''lmaydi, uyqusizlik tufayli odam charchaydi: avval sabab, keyin natija. «Yomg''ir — bulut»da esa avval natija, keyin sabab.',
   'Из-за засухи — неурожай, из-за бессонницы — усталость: сначала причина, потом следствие. В паре «дождь — туча» наоборот.',
   'draft'),
  ('v084',
   'relation',
   5,
   'Bu ikki so''z qanday bog''langan?',
   'Botir — jasur',
   array['ma''nosi qarama-qarshi', 'qism va butun', 'biri ikkinchisining sababi', 'ma''nosi yaqin']::text[],
   'Как связаны эти два слова?',
   'Храбрый — отважный',
   array['противоположные по смыслу', 'часть и целое', 'одно — причина другого', 'близкие по смыслу']::text[],
   3,
   'Botir va jasur — ma''nosi yaqin so''zlar (sinonimlar).',
   '«Храбрый» и «отважный» — слова, близкие по смыслу (синонимы).',
   'draft'),
  ('v085',
   'relation',
   5,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Muallif — kitob',
   array['Kitobxon — kitob', 'Kitob — sahifa', 'Qalam — daftar', 'Bastakor — kuy']::text[],
   'В какой паре слова связаны так же?',
   'Автор — книга',
   array['Читатель — книга', 'Книга — страница', 'Карандаш — тетрадь', 'Композитор — мелодия']::text[],
   3,
   'Muallif kitobni, bastakor kuyni yaratadi: ijodkor va uning asari.',
   'Автор создаёт книгу, композитор — мелодию: создатель и его произведение.',
   'draft'),
  ('v087',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Tarozi : og''irlik = chizg''ich : ?',
   array['santimetr', 'qalam', 'uzunlik', 'to''g''ri']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Весы : вес = линейка : ?',
   array['сантиметр', 'карандаш', 'длина', 'прямая']::text[],
   2,
   'Tarozi og''irlikni, chizg''ich uzunlikni o''lchaydi. Santimetr — o''lchov birligi, kattalikning o''zi emas.',
   'Весы измеряют вес, линейка — длину. Сантиметр — единица измерения, а не сама величина.',
   'draft'),
  ('v088',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Ko''prik : daryo = tunnel : ?',
   array['tog''', 'poyezd', 'qorong''ilik', 'yo''l']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Мост : река = тоннель : ?',
   array['гора', 'поезд', 'темнота', 'дорога']::text[],
   0,
   'Ko''prik daryo ustidan, tunnel tog'' ichidan o''tishga yordam beradi: inshoot va u yengib o''tadigan to''siq.',
   'Мост позволяет пройти над рекой, тоннель — сквозь гору: сооружение и препятствие, которое оно преодолевает.',
   'draft'),
  ('v089',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kitob : o''qimoq = kuy : ?',
   array['tinglamoq', 'nota', 'quloq', 'karnay']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Книга : читать = мелодия : ?',
   array['слушать', 'ноты', 'ухо', 'труба']::text[],
   0,
   'Kitobni o''qiymiz, kuyni tinglaymiz: asar va uni qabul qilish usuli.',
   'Книгу читают, мелодию слушают: произведение и способ его восприятия.',
   'draft'),
  ('v090',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Mashq : mahorat = o''qish : ?',
   array['kitob', 'maktab', 'bilim', 'imtihon']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Тренировка : мастерство = учёба : ?',
   array['книга', 'школа', 'знания', 'экзамен']::text[],
   2,
   'Mashq qilish mahoratga, o''qish esa bilimga olib keladi: harakat va uning natijasi.',
   'Тренировка приводит к мастерству, учёба — к знаниям: действие и его результат.',
   'draft'),
  ('v091',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Oshpaz : retsept = quruvchi : ?',
   array['g''isht', 'chizma', 'uy', 'kran']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Повар : рецепт = строитель : ?',
   array['кирпич', 'чертёж', 'дом', 'кран']::text[],
   1,
   'Oshpaz retseptga qarab pishiradi, quruvchi chizmaga qarab quradi: usta va u amal qiladigan ko''rsatma.',
   'Повар готовит по рецепту, строитель строит по чертежу: мастер и инструкция, по которой он работает.',
   'draft'),
  ('v092',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Ildiz : daraxt = poydevor : ?',
   array['g''isht', 'yer', 'tom', 'bino']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Корень : дерево = фундамент : ?',
   array['кирпич', 'земля', 'крыша', 'здание']::text[],
   3,
   'Ildiz daraxtni, poydevor binoni ushlab turadi: tayanch va u ushlab turgan narsa.',
   'Корень держит дерево, фундамент — здание: опора и то, что она держит.',
   'draft'),
  ('v093',
   'odd',
   6,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['g''isht', 'taxta', 'sement', 'bolg''a']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['кирпич', 'доска', 'цемент', 'молоток']::text[],
   3,
   'G''isht, taxta va sement — qurilish materiallari, bolg''a esa asbob.',
   'Кирпич, доска и цемент — строительные материалы, а молоток — инструмент.',
   'draft'),
  ('v094',
   'odd',
   6,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sevinch', 'xotira', 'g''azab', 'qo''rquv']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['радость', 'память', 'гнев', 'страх']::text[],
   1,
   'Sevinch, g''azab va qo''rquv — his-tuyg''ular, xotira esa his-tuyg''u emas.',
   'Радость, гнев и страх — чувства, а память — нет.',
   'draft'),
  ('v095',
   'odd',
   6,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['ko''rish', 'eshitish', 'yurish', 'hid bilish']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['зрение', 'слух', 'ходьба', 'обоняние']::text[],
   2,
   'Ko''rish, eshitish va hid bilish — sezgilar, yurish esa harakat.',
   'Зрение, слух и обоняние — чувства восприятия, а ходьба — движение.',
   'draft'),
  ('v096',
   'odd',
   6,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['mikrofon', 'barometr', 'termometr', 'spidometr']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['микрофон', 'барометр', 'термометр', 'спидометр']::text[],
   0,
   'Barometr, termometr va spidometr nimanidir o''lchaydi, mikrofon esa ovozni qabul qilib uzatadi.',
   'Барометр, термометр и спидометр что-то измеряют, а микрофон улавливает и передаёт звук.',
   'draft'),
  ('v097',
   'category',
   6,
   'Qaysi so''z shu guruhga kiradi?',
   'Keng, uzun, baland',
   array['chuqur', 'og''ir', 'qizil', 'tez']::text[],
   'Какое слово относится к этой группе?',
   'Широкий, длинный, высокий',
   array['глубокий', 'тяжёлый', 'красный', 'быстрый']::text[],
   0,
   'Guruhdagilar narsaning qaysidir yo''nalishdagi o''lchamini bildiradi. Chuqur ham shunday; og''ir — vazn, o''lcham emas.',
   'В группе — размеры предмета в каком-то направлении. «Глубокий» тоже; «тяжёлый» — это вес, а не размер.',
   'draft'),
  ('v098',
   'category',
   6,
   'Qaysi so''z shu guruhga kiradi?',
   'Soat, kalendar, qum soat',
   array['tarozi', 'chizg''ich', 'sekundomer', 'kompas']::text[],
   'Какое слово относится к этой группе?',
   'Часы, календарь, песочные часы',
   array['весы', 'линейка', 'секундомер', 'компас']::text[],
   2,
   'Guruhdagilar vaqtni o''lchashga yordam beradi. Sekundomer ham shunday.',
   'Всё в группе помогает измерять время. Секундомер тоже.',
   'draft'),
  ('v099',
   'category',
   6,
   'Qaysi so''z shu guruhga kiradi?',
   'O''pka, yurak, jigar',
   array['tirnoq', 'oshqozon', 'soch', 'qosh']::text[],
   'Какое слово относится к этой группе?',
   'Лёгкие, сердце, печень',
   array['ноготь', 'желудок', 'волосы', 'бровь']::text[],
   1,
   'Guruhdagilar — tananing ichki a''zolari. Oshqozon ham ichki a''zo.',
   'В группе — внутренние органы. Желудок тоже внутренний орган.',
   'draft'),
  ('v100',
   'relation',
   6,
   'Bu ikki so''z qanday bog''langan?',
   'Sham — mum',
   array['joy va u yerdagi narsa', 'asbob va uning vazifasi', 'ma''nosi qarama-qarshi', 'narsa va u yasalgan material']::text[],
   'Как связаны эти два слова?',
   'Свеча — воск',
   array['место и то, что там находится', 'инструмент и его назначение', 'противоположные по смыслу', 'предмет и материал, из которого он сделан']::text[],
   3,
   'Sham mumdan yasaladi.',
   'Свечу делают из воска.',
   'draft'),
  ('v101',
   'relation',
   6,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Spidometr — tezlik',
   array['Haydovchi — mashina', 'Tezlik — yo''l', 'Soat — devor', 'Soat — vaqt']::text[],
   'В какой паре слова связаны так же?',
   'Спидометр — скорость',
   array['Водитель — машина', 'Скорость — дорога', 'Часы — стена', 'Часы — время']::text[],
   3,
   'Spidometr tezlikni, soat esa vaqtni ko''rsatadi: asbob va u o''lchaydigan kattalik.',
   'Спидометр показывает скорость, часы — время: прибор и величина, которую он измеряет.',
   'draft'),
  ('v102',
   'relation',
   6,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Ochlik — ovqat',
   array['Ovqat — likopcha', 'Chanqoq — suv', 'Oshpaz — ovqat', 'Non — bug''doy']::text[],
   'В какой паре слова связаны так же?',
   'Голод — еда',
   array['Еда — тарелка', 'Жажда — вода', 'Повар — еда', 'Хлеб — пшеница']::text[],
   1,
   'Ochlikni ovqat, chanqoqni suv qondiradi: ehtiyoj va uni qondiradigan narsa.',
   'Голод утоляет еда, жажду — вода: потребность и то, что её удовлетворяет.',
   'draft'),
  ('v103',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Yomg''ir : jala = shamol : ?',
   array['shabada', 'bulut', 'bo''ron', 'momaqaldiroq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Дождь : ливень = ветер : ?',
   array['ветерок', 'туча', 'ураган', 'гром']::text[],
   2,
   'Jala — juda kuchli yomg''ir, bo''ron — juda kuchli shamol. Shabada esa kuchsiz shamol, munosabat teskari.',
   'Ливень — очень сильный дождь, ураган — очень сильный ветер. Ветерок — слабый ветер, это обратная связь.',
   'draft'),
  ('v104',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Sahifa : kitob = kadr : ?',
   array['film', 'kamera', 'rasm', 'ekran']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Страница : книга = кадр : ?',
   array['фильм', 'камера', 'фотография', 'экран']::text[],
   0,
   'Kitob ko''p sahifalardan, film esa ko''p kadrlardan tashkil topadi: birlik va ulardan tuzilgan butun.',
   'Книга состоит из многих страниц, фильм — из многих кадров: единица и целое из таких единиц.',
   'draft'),
  ('v105',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qo''rquv : jasorat = dangasalik : ?',
   array['tirishqoqlik', 'charchoq', 'uyqu', 'dam olish']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Страх : смелость = лень : ?',
   array['трудолюбие', 'усталость', 'сон', 'отдых']::text[],
   0,
   'Jasorat qo''rquvning, tirishqoqlik dangasalikning qarama-qarshisi.',
   'Смелость противоположна страху, трудолюбие — лени.',
   'draft'),
  ('v107',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Saxiy : ziqna = kamtar : ?',
   array['uyatchan', 'maqtanchoq', 'jasur', 'sodda']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Щедрый : жадный = скромный : ?',
   array['застенчивый', 'хвастливый', 'смелый', 'простой']::text[],
   1,
   'Saxiy — ziqnaning, kamtar — maqtanchoqning qarama-qarshisi. Uyatchan esa kamtarga yaqin.',
   'Щедрый противоположен жадному, скромный — хвастливому. «Застенчивый» же близок к «скромному».',
   'draft'),
  ('v108',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Tomir : qon = quvur : ?',
   array['temir', 'uy', 'jo''mrak', 'suv']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Вена : кровь = труба : ?',
   array['железо', 'дом', 'кран', 'вода']::text[],
   3,
   'Qon tomir bo''ylab, suv esa quvur bo''ylab oqadi: yo''l va u bo''ylab oqadigan suyuqlik.',
   'Кровь течёт по вене, вода — по трубе: канал и жидкость, которая по нему течёт.',
   'draft'),
  ('v109',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Urug'' : ekmoq = hosil : ?',
   array['sug''ormoq', 'dala', 'bug''doy', 'yig''moq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Семена : сеять = урожай : ?',
   array['поливать', 'поле', 'пшеница', 'собирать']::text[],
   3,
   'Urug'' ekiladi, hosil yig''iladi: dehqonchilikning boshidagi va oxiridagi ish.',
   'Семена сеют, урожай собирают: первое и последнее дело в земледелии.',
   'draft'),
  ('v110',
   'odd',
   7,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['oldin', 'bu yerda', 'keyin', 'hozir']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['раньше', 'здесь', 'позже', 'сейчас']::text[],
   1,
   'Oldin, keyin va hozir — vaqtni, «bu yerda» esa joyni bildiradi.',
   '«Раньше», «позже» и «сейчас» говорят о времени, а «здесь» — о месте.',
   'draft'),
  ('v111',
   'odd',
   7,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['kub', 'piramida', 'kvadrat', 'prizma']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['куб', 'пирамида', 'квадрат', 'призма']::text[],
   2,
   'Kub, piramida va prizma — hajmli jismlar, kvadrat esa tekis shakl.',
   'Куб, пирамида и призма — объёмные тела, а квадрат — плоская фигура.',
   'draft'),
  ('v112',
   'odd',
   7,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['unutmoq', 'tushunmoq', 'anglamoq', 'fahmlamoq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['забывать', 'понимать', 'осознавать', 'постигать']::text[],
   0,
   'Tushunmoq, anglamoq va fahmlamoq — ma''nosi yaqin so''zlar, unutmoq esa ulardan farq qiladi.',
   '«Понимать», «осознавать» и «постигать» близки по смыслу, а «забывать» — нет.',
   'draft'),
  ('v113',
   'odd',
   7,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['talaba', 'o''qituvchi', 'shifokor', 'muhandis']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['студент', 'учитель', 'врач', 'инженер']::text[],
   0,
   'O''qituvchi, shifokor va muhandis — kasb egalari, talaba esa hali kasb o''rganayotgan odam.',
   'Учитель, врач и инженер — профессии, а студент ещё только учится профессии.',
   'draft'),
  ('v114',
   'category',
   7,
   'Qaysi so''z shu guruhga kiradi?',
   'Yo''lbars, zebra, asalari',
   array['pomidor', 'qor', 'tarvuz', 'bulut']::text[],
   'Какое слово относится к этой группе?',
   'Тигр, зебра, пчела',
   array['помидор', 'снег', 'арбуз', 'облако']::text[],
   2,
   'Guruhdagilarning umumiy belgisi — yo''l-yo''l (chiziqli) ko''rinish. Variantlardan faqat tarvuz ham yo''l-yo''l.',
   'Общий признак группы — полоски. Из вариантов полосатый только арбуз.',
   'draft'),
  ('v115',
   'category',
   7,
   'Qaysi so''z shu guruhga kiradi?',
   'Ko''mir, neft, gaz',
   array['g''isht', 'o''tin', 'shisha', 'paxta']::text[],
   'Какое слово относится к этой группе?',
   'Уголь, нефть, газ',
   array['кирпич', 'дрова', 'стекло', 'хлопок']::text[],
   1,
   'Guruhdagilar — yoqilg''i. O''tin ham yoqilg''i.',
   'В группе — топливо. Дрова тоже топливо.',
   'draft'),
  ('v116',
   'category',
   7,
   'Qaysi so''z shu guruhga kiradi?',
   'Qor, sut, paxta',
   array['ko''mir', 'osmon', 'maysa', 'bo''r']::text[],
   'Какое слово относится к этой группе?',
   'Снег, молоко, хлопок',
   array['уголь', 'небо', 'трава', 'мел']::text[],
   3,
   'Guruhdagilarning umumiy belgisi — oq rang. Bo''r ham oq.',
   'Общий признак группы — белый цвет. Мел тоже белый.',
   'draft'),
  ('v117',
   'relation',
   7,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Daraxt — o''rmon',
   array['Barg — yashil', 'O''rmon — bo''ri', 'Daraxt — yog''och', 'Qo''y — suruv']::text[],
   'В какой паре слова связаны так же?',
   'Дерево — лес',
   array['Лист — зелёный', 'Лес — волк', 'Дерево — древесина', 'Овца — отара']::text[],
   3,
   'O''rmon ko''p daraxtlardan, suruv ko''p qo''ylardan iborat: bitta va ularning to''plami.',
   'Лес состоит из многих деревьев, отара — из многих овец: один и их множество.',
   'draft'),
  ('v118',
   'relation',
   7,
   'Bu ikki so''z qanday bog''langan?',
   'Ehtiyotsizlik — xato',
   array['ma''nosi yaqin', 'sabab va natija', 'ma''nosi qarama-qarshi', 'qism va butun']::text[],
   'Как связаны эти два слова?',
   'Невнимательность — ошибка',
   array['близкие по смыслу', 'причина и следствие', 'противоположные по смыслу', 'часть и целое']::text[],
   1,
   'Ehtiyotsizlik tufayli xato qilinadi: biri ikkinchisining sababi.',
   'Из-за невнимательности совершают ошибки: одно — причина другого.',
   'draft'),
  ('v119',
   'relation',
   7,
   'Bu ikki so''z qanday bog''langan?',
   'Transport — velosiped',
   array['qism va butun', 'sabab va natija', 'umumiy tushuncha va uning bir turi', 'asbob va uning vazifasi']::text[],
   'Как связаны эти два слова?',
   'Транспорт — велосипед',
   array['часть и целое', 'причина и следствие', 'общее понятие и один из его видов', 'инструмент и его назначение']::text[],
   2,
   'Velosiped — transportning bir turi, uning qismi emas.',
   'Велосипед — один из видов транспорта, а не его часть.',
   'draft'),
  ('v120',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kechikish : uzr = sovg''a : ?',
   array['minnatdorchilik', 'bayram', 'quti', 'pul']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Опоздание : извинение = подарок : ?',
   array['благодарность', 'праздник', 'коробка', 'деньги']::text[],
   0,
   'Kechiksak uzr so''raymiz, sovg''a olsak minnatdorchilik bildiramiz: vaziyat va unga odobli javob.',
   'Опоздав, мы извиняемся, получив подарок — благодарим: ситуация и вежливый ответ на неё.',
   'draft'),
  ('v121',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Tushunmovchilik : tushuntirish = qorong''ilik : ?',
   array['yorug''lik', 'tun', 'qo''rquv', 'ko''z']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Непонимание : объяснение = темнота : ?',
   array['свет', 'ночь', 'страх', 'глаза']::text[],
   0,
   'Tushuntirish tushunmovchilikni, yorug''lik qorong''ilikni yo''qotadi: holat va uni bartaraf etadigan narsa.',
   'Объяснение устраняет непонимание, свет — темноту: состояние и то, что его устраняет.',
   'draft'),
  ('v123',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Bo''yoq : rassom = so''z : ?',
   array['lug''at', 'yozuvchi', 'harf', 'kitob']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Краски : художник = слова : ?',
   array['словарь', 'писатель', 'буква', 'книга']::text[],
   1,
   'Rassom bo''yoq bilan, yozuvchi so''z bilan ijod qiladi: material va u bilan ishlaydigan ijodkor.',
   'Художник творит красками, писатель — словами: материал и творец, который с ним работает.',
   'draft'),
  ('v124',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Retsept : taom = nota : ?',
   array['qalam', 'pianino', 'qo''shiqchi', 'kuy']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Рецепт : блюдо = ноты : ?',
   array['карандаш', 'пианино', 'певец', 'мелодия']::text[],
   3,
   'Retsept bo''yicha taom tayyorlanadi, nota bo''yicha kuy ijro etiladi: yozma ko''rsatma va uning natijasi.',
   'По рецепту готовят блюдо, по нотам исполняют мелодию: запись-инструкция и её результат.',
   'draft'),
  ('v125',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Shoshilish : xato = ehtiyotkorlik : ?',
   array['tezlik', 'qo''rquv', 'shoshilish', 'aniqlik']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Спешка : ошибка = осторожность : ?',
   array['скорость', 'страх', 'спешка', 'точность']::text[],
   3,
   'Shoshilish xatoga, ehtiyotkorlik aniqlikka olib keladi: xulq va uning oqibati.',
   'Спешка ведёт к ошибке, осторожность — к точности: поведение и его последствие.',
   'draft'),
  ('v126',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Xarita : hudud = chizma : ?',
   array['qalam', 'bino', 'me''mor', 'qog''oz']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Карта : местность = чертёж : ?',
   array['карандаш', 'здание', 'архитектор', 'бумага']::text[],
   1,
   'Xarita hududni, chizma binoni qog''ozda tasvirlaydi: tasvir va u ko''rsatadigan narsa.',
   'Карта изображает местность, чертёж — здание: изображение и то, что на нём показано.',
   'draft'),
  ('v127',
   'odd',
   8,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['pichirlash', 'nutq', 'imo-ishora', 'qichqiriq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['шёпот', 'речь', 'жест', 'крик']::text[],
   2,
   'Pichirlash, nutq va qichqiriqda ovoz ishlatiladi, imo-ishora esa ovozsiz.',
   'В шёпоте, речи и крике участвует голос, а жест беззвучен.',
   'draft'),
  ('v128',
   'odd',
   8,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['doim', 'kecha', 'bugun', 'ertaga']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['всегда', 'вчера', 'сегодня', 'завтра']::text[],
   0,
   'Kecha, bugun va ertaga — aniq kunlar, «doim» esa har qanday vaqtni bildiradi.',
   '«Вчера», «сегодня» и «завтра» — конкретные дни, а «всегда» — любое время.',
   'draft'),
  ('v129',
   'odd',
   8,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sinmoq', 'gullamoq', 'o''smoq', 'ko''karmoq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['ломаться', 'цвести', 'расти', 'зеленеть']::text[],
   0,
   'Gullamoq, o''smoq va ko''karmoq — o''simlikning rivojlanishi, sinmoq esa buzilish.',
   'Цвести, расти и зеленеть — развитие растения, а ломаться — разрушение.',
   'draft'),
  ('v130',
   'odd',
   8,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['eshitmoq', 'tinglamoq', 'gapirmoq', 'quloq solmoq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['слышать', 'слушать', 'говорить', 'прислушиваться']::text[],
   2,
   'Eshitmoq, tinglamoq va quloq solmoq — ovozni qabul qilish, gapirmoq esa ovoz chiqarish.',
   'Слышать, слушать и прислушиваться — воспринимать звук, а говорить — издавать его.',
   'draft'),
  ('v131',
   'category',
   8,
   'Qaysi so''z shu guruhga kiradi?',
   'Yulduz, quyosh, olov',
   array['oy', 'chiroq', 'oyna', 'olmos']::text[],
   'Какое слово относится к этой группе?',
   'Звезда, солнце, огонь',
   array['луна', 'лампа', 'зеркало', 'алмаз']::text[],
   1,
   'Guruhdagilar o''zidan yorug''lik chiqaradi. Chiroq ham shunday. Oy, oyna va olmos esa boshqa manbaning yorug''ligini qaytaradi.',
   'Всё в группе само излучает свет. Лампа тоже. Луна, зеркало и алмаз лишь отражают чужой свет.',
   'draft'),
  ('v133',
   'category',
   8,
   'Qaysi so''z shu guruhga kiradi?',
   'Muqaddima, bob, xotima',
   array['muallif', 'nashriyot', 'kitobxon', 'mundarija']::text[],
   'Какое слово относится к этой группе?',
   'Вступление, глава, заключение',
   array['автор', 'издательство', 'читатель', 'оглавление']::text[],
   3,
   'Guruhdagilar — kitobning qismlari. Mundarija ham kitobning qismi; qolganlari kitobdan tashqarida.',
   'В группе — части книги. Оглавление тоже часть книги; остальное находится вне её.',
   'draft'),
  ('v134',
   'relation',
   8,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Muqova — kitob',
   array['Kitob — kitobxon', 'Po''st — apelsin', 'Kitob — javon', 'Muallif — kitob']::text[],
   'В какой паре слова связаны так же?',
   'Обложка — книга',
   array['Книга — читатель', 'Кожура — апельсин', 'Книга — полка', 'Автор — книга']::text[],
   1,
   'Muqova kitobni, po''st apelsinni tashqaridan o''rab himoya qiladi.',
   'Обложка защищает книгу снаружи, кожура — апельсин.',
   'draft'),
  ('v135',
   'relation',
   8,
   'Bu ikki so''z qanday bog''langan?',
   'Harorat — gradus',
   array['asbob va u o''lchaydigan kattalik', 'qism va butun', 'kattalik va uning o''lchov birligi', 'sabab va natija']::text[],
   'Как связаны эти два слова?',
   'Температура — градус',
   array['прибор и величина, которую он измеряет', 'часть и целое', 'величина и её единица измерения', 'причина и следствие']::text[],
   2,
   'Harorat gradusda o''lchanadi: gradus — o''lchov birligi, asbob emas.',
   'Температуру измеряют в градусах: градус — единица измерения, а не прибор.',
   'draft'),
  ('v136',
   'relation',
   8,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Xato — tuzatish',
   array['Kir — yuvish', 'Xato — o''qituvchi', 'Tuzatish — qalam', 'Kir — ko''ylak']::text[],
   'В какой паре слова связаны так же?',
   'Ошибка — исправление',
   array['Грязь — стирка', 'Ошибка — учитель', 'Исправление — карандаш', 'Грязь — рубашка']::text[],
   0,
   'Xato tuzatish bilan, kir yuvish bilan yo''qotiladi: muammo va uni bartaraf etish.',
   'Ошибку устраняет исправление, грязь — стирка: проблема и её устранение.',
   'draft'),
  ('v137',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Hech kim : hamma = hech qachon : ?',
   array['doim', 'ba''zan', 'hozir', 'ko''pincha']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Никто : все = никогда : ?',
   array['всегда', 'иногда', 'сейчас', 'часто']::text[],
   0,
   '«Hech kim» va «hamma» — odamlar bo''yicha ikki chekka; vaqt bo''yicha ularga «hech qachon» va «doim» mos keladi.',
   '«Никто» и «все» — две крайности по людям; по времени им соответствуют «никогда» и «всегда».',
   'draft'),
  ('v138',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Urug'' : nihol = nihol : ?',
   array['urug''', 'tuproq', 'daraxt', 'suv']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Семя : росток = росток : ?',
   array['семя', 'почва', 'дерево', 'вода']::text[],
   2,
   'Har safar bir bosqich oldinga: urug''dan nihol, niholdan daraxt o''sadi. «Urug''» — orqaga qaytish.',
   'Каждый раз на одну стадию вперёд: из семени — росток, из ростка — дерево. «Семя» — шаг назад.',
   'draft'),
  ('v139',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qisqa : qisqartirmoq = keng : ?',
   array['toraytirmoq', 'kengaytirmoq', 'kenglik', 'uzaytirmoq']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Короткий : укорачивать = широкий : ?',
   array['сужать', 'расширять', 'ширина', 'удлинять']::text[],
   1,
   'Qisqartirmoq — qisqa qilmoq, kengaytirmoq — keng qilmoq: belgi va narsaga shu belgini berish.',
   'Укорачивать — делать коротким, расширять — делать широким: признак и действие, которое его придаёт.',
   'draft'),
  ('v140',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Muammo : yechim = kasallik : ?',
   array['kasalxona', 'shifokor', 'alomat', 'davo']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Проблема : решение = болезнь : ?',
   array['больница', 'врач', 'симптом', 'лечение']::text[],
   3,
   'Muammoni yechim, kasallikni davo bartaraf etadi. Shifokor — davolovchi odam, davoning o''zi emas.',
   'Проблему устраняет решение, болезнь — лечение. Врач — человек, который лечит, а не само лечение.',
   'draft'),
  ('v142',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Isitma : kasallik = tutun : ?',
   array['mo''ri', 'olov', 'kul', 'havo']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Жар : болезнь = дым : ?',
   array['дымоход', 'огонь', 'пепел', 'воздух']::text[],
   1,
   'Isitma kasallik borligini, tutun olov borligini bildiradi: belgi va uning sababi.',
   'Жар говорит о болезни, дым — об огне: признак и его причина.',
   'draft'),
  ('v143',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kirish : chiqish = havoga ko''tarilish : ?',
   array['osmon', 'uchuvchi', 'qo''nish', 'aeroport']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Вход : выход = взлёт : ?',
   array['небо', 'лётчик', 'посадка', 'аэропорт']::text[],
   2,
   'Kirish va chiqish — qarama-qarshi harakatlar. Samolyotning havoga ko''tarilishiga qarama-qarshi harakat — qo''nish.',
   'Вход и выход — противоположные действия. Противоположность взлёту самолёта — посадка.',
   'draft'),
  ('v144',
   'odd',
   9,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['ba''zi', 'hamma', 'har bir', 'barcha']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['некоторые', 'все', 'каждый', 'всякий']::text[],
   0,
   'Hamma, har bir va barcha — to''liq qamrovni, «ba''zi» esa faqat bir qismini bildiradi.',
   '«Все», «каждый» и «всякий» охватывают всех, а «некоторые» — только часть.',
   'draft'),
  ('v145',
   'odd',
   9,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['tarqalmoq', 'yig''ilmoq', 'to''planmoq', 'jamlanmoq']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['расходиться', 'собираться', 'скапливаться', 'сходиться']::text[],
   0,
   'Yig''ilmoq, to''planmoq va jamlanmoq — bir joyga kelish, tarqalmoq esa aksincha.',
   'Собираться, скапливаться и сходиться — сближаться в одном месте, а расходиться — наоборот.',
   'draft'),
  ('v146',
   'odd',
   9,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['yarim', 'chorak', 'juft', 'uchdan bir']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['половина', 'четверть', 'пара', 'треть']::text[],
   2,
   'Yarim, chorak va uchdan bir — butunning bir ulushi, juft esa ikkita narsa.',
   'Половина, четверть и треть — доли целого, а пара — два предмета.',
   'draft'),
  ('v147',
   'odd',
   9,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['sabab', 'oqibat', 'asos', 'manba']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['причина', 'последствие', 'основание', 'источник']::text[],
   1,
   'Sabab, asos va manba — biror narsaning boshlanishi, oqibat esa uning natijasi.',
   'Причина, основание и источник — то, из чего что-то происходит, а последствие — результат.',
   'draft'),
  ('v148',
   'category',
   9,
   'Qaysi so''z shu guruhga kiradi?',
   'Tong, bahor, bolalik',
   array['kechqurun', 'qarilik', 'xotima', 'muqaddima']::text[],
   'Какое слово относится к этой группе?',
   'Рассвет, весна, детство',
   array['вечер', 'старость', 'заключение', 'вступление']::text[],
   3,
   'Guruhdagilar — nimaningdir boshlanishi: kunning, yilning, hayotning. Muqaddima ham kitobning boshlanishi.',
   'В группе — начало чего-то: дня, года, жизни. Вступление — тоже начало книги.',
   'draft'),
  ('v149',
   'category',
   9,
   'Qaysi so''z shu guruhga kiradi?',
   'Muz, qor, do''l',
   array['bug''', 'yomg''ir', 'tuman', 'qirov']::text[],
   'Какое слово относится к этой группе?',
   'Лёд, снег, град',
   array['пар', 'дождь', 'туман', 'иней']::text[],
   3,
   'Guruhdagilar — muzlagan, qattiq holatdagi suv. Qirov ham shunday; bug'', yomg''ir va tuman esa qattiq emas.',
   'В группе — замёрзшая, твёрдая вода. Иней тоже; пар, дождь и туман — не твёрдые.',
   'draft'),
  ('v150',
   'category',
   9,
   'Qaysi so''z shu guruhga kiradi?',
   'Kalit, parol, ruxsatnoma',
   array['qulf', 'chipta', 'to''siq', 'devor']::text[],
   'Какое слово относится к этой группе?',
   'Ключ, пароль, пропуск',
   array['замок', 'билет', 'шлагбаум', 'стена']::text[],
   1,
   'Guruhdagilar kirishga ruxsat beradi. Chipta ham shunday; qulf, to''siq va devor esa kirishni to''sadi.',
   'Всё в группе даёт право войти. Билет тоже; замок, шлагбаум и стена, наоборот, преграждают путь.',
   'draft'),
  ('v151',
   'relation',
   9,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Harf — so''z',
   array['Qalam — harf', 'So''z — ma''no', 'Nota — kuy', 'Kitob — muallif']::text[],
   'В какой паре слова связаны так же?',
   'Буква — слово',
   array['Карандаш — буква', 'Слово — смысл', 'Нота — мелодия', 'Книга — автор']::text[],
   2,
   'So''z harflardan, kuy notalardan tuziladi: kichik birlik va undan tuzilgan butun.',
   'Слово складывается из букв, мелодия — из нот: мелкая единица и целое из таких единиц.',
   'draft'),
  ('v152',
   'relation',
   9,
   'Bu ikki so''z qanday bog''langan?',
   'Chizma — bino',
   array['reja va unga ko''ra yaratiladigan narsa', 'qism va butun', 'narsa va uning materiali', 'asbob va u bilan ishlaydigan odam']::text[],
   'Как связаны эти два слова?',
   'Чертёж — здание',
   array['план и то, что создаётся по нему', 'часть и целое', 'предмет и его материал', 'инструмент и тот, кто им работает']::text[],
   0,
   'Bino chizmaga qarab quriladi: chizma — reja, bino — shu reja bo''yicha yaratilgan narsa.',
   'Здание строят по чертежу: чертёж — план, здание — то, что создано по этому плану.',
   'draft'),
  ('v153',
   'relation',
   9,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Soya — narsa',
   array['Aks-sado — ovoz', 'Quyosh — yorug''lik', 'Soya — salqin', 'Daraxt — soya']::text[],
   'В какой паре слова связаны так же?',
   'Тень — предмет',
   array['Эхо — звук', 'Солнце — свет', 'Тень — прохлада', 'Дерево — тень']::text[],
   0,
   'Soya narsadan, aks-sado ovozdan hosil bo''ladi: avval hosila, keyin u kelib chiqqan narsa. «Daraxt — soya»da tartib teskari, «Soya — salqin»da esa soya — sabab, salqin — uning natijasi.',
   'Тень возникает от предмета, эхо — от звука: сначала производное, потом его источник. В паре «дерево — тень» порядок обратный, а в паре «тень — прохлада» тень — причина, прохлада — её следствие.',
   'draft'),
  ('v154',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Iliq : issiq : qaynoq = salqin : sovuq : ?',
   array['iliq', 'qor', 'muzdek', 'qish']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Тёплый : горячий : раскалённый = прохладный : холодный : ?',
   array['тёплый', 'снег', 'ледяной', 'зима']::text[],
   2,
   'Har qatorda belgi bosqichma-bosqich kuchayadi: iliq → issiq → qaynoq; salqin → sovuq → muzdek.',
   'В каждом ряду признак усиливается шаг за шагом: тёплый → горячий → раскалённый; прохладный → холодный → ледяной.',
   'draft'),
  ('v160',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kecha : ertaga = o''tmish : ?',
   array['kelajak', 'hozir', 'tarix', 'vaqt']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Вчера : завтра = прошлое : ?',
   array['будущее', 'настоящее', 'история', 'время']::text[],
   0,
   'Kecha — o''tgan kun, ertaga — keladigan kun. Xuddi shunday, o''tmishning qarama-qarshisi — kelajak; «hozir» ikkalasining o''rtasida.',
   'Вчера — прошедший день, завтра — будущий. Так же прошлому противоположно будущее; «настоящее» — между ними.',
   'draft'),
  ('v161',
   'odd',
   10,
   'Qaysi juftlik ortiqcha?',
   'Uchta juftlikda so''zlar bir xil bog''langan, bittasida esa boshqacha.',
   array['Yaxshi — a''lo', 'Issiq — sovuq', 'Baland — past', 'Yorug'' — qorong''i']::text[],
   'Какая пара лишняя?',
   'В трёх парах слова связаны одинаково, а в одной — по-другому.',
   array['Хороший — отличный', 'Горячий — холодный', 'Высокий — низкий', 'Светлый — тёмный']::text[],
   0,
   'Uchta juftlikdagi so''zlar ma''nosi qarama-qarshi, «yaxshi — a''lo»da esa bir belgining kuchsiz va kuchli darajasi.',
   'В трёх парах слова противоположны, а «хороший — отличный» — слабая и сильная степень одного признака.',
   'draft'),
  ('v162',
   'odd',
   10,
   'Qaysi juftlik ortiqcha?',
   'Uchta juftlikda so''zlar bir xil bog''langan, bittasida esa boshqacha.',
   array['Barmoq — qo''l', 'G''ildirak — mashina', 'Olma — meva', 'Sahifa — kitob']::text[],
   'Какая пара лишняя?',
   'В трёх парах слова связаны одинаково, а в одной — по-другому.',
   array['Палец — рука', 'Колесо — машина', 'Яблоко — фрукт', 'Страница — книга']::text[],
   2,
   'Uchta juftlikda birinchi so''z ikkinchisining qismi. Olma esa mevaning qismi emas, uning bir turi.',
   'В трёх парах первое слово — часть второго. Яблоко же не часть фрукта, а его вид.',
   'draft'),
  ('v163',
   'odd',
   10,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['chunki', 'lekin', 'sababli', 'tufayli']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['потому что', 'но', 'так как', 'поскольку']::text[],
   1,
   '«Chunki», «sababli», «tufayli» sababni bildiradi, «lekin» esa qarama-qarshilikni.',
   '«Потому что», «так как», «поскольку» указывают на причину, а «но» — на противопоставление.',
   'draft'),
  ('v164',
   'odd',
   10,
   'Qaysi so''z ortiqcha?',
   'Uchta so''z bitta guruhga kiradi, bittasi esa kirmaydi.',
   array['taxmin', 'faraz', 'gipoteza', 'dalil']::text[],
   'Какое слово лишнее?',
   'Три слова относятся к одной группе, а одно — нет.',
   array['догадка', 'предположение', 'гипотеза', 'доказательство']::text[],
   3,
   'Taxmin, faraz va gipoteza — hali isbotlanmagan fikr, dalil esa fikrni isbotlaydi.',
   'Догадка, предположение и гипотеза — ещё не доказанные мысли, а доказательство подтверждает мысль.',
   'draft'),
  ('v165',
   'category',
   10,
   'Qaysi so''z shu guruhga kiradi?',
   'Ehtimol, balki, aftidan',
   array['albatta', 'aniq', 'shubhasiz', 'shekilli']::text[],
   'Какое слово относится к этой группе?',
   'Вероятно, возможно, по-видимому',
   array['конечно', 'точно', 'несомненно', 'кажется']::text[],
   3,
   'Guruhdagi so''zlar ishonch to''liq emasligini (taxminni) bildiradi. «Shekilli» ham shunday, qolganlari esa to''liq ishonchni.',
   'Слова группы выражают неполную уверенность (предположение). «Кажется» тоже, а остальные — полную уверенность.',
   'draft'),
  ('v166',
   'category',
   10,
   'Qaysi juftlik shu guruhga kiradi?',
   'Urug'' — daraxt; tuxum — qush; bola — katta odam',
   array['It — kuchukcha', 'Kuchukcha — it', 'Daraxt — o''rmon', 'Qush — uya']::text[],
   'Какая пара относится к этой группе?',
   'Семя — дерево; яйцо — птица; ребёнок — взрослый',
   array['Собака — щенок', 'Щенок — собака', 'Дерево — лес', 'Птица — гнездо']::text[],
   1,
   'Har juftlikda avval boshlang''ich bosqich, keyin undan o''sib chiqadigan jonzot. «It — kuchukcha»da tartib teskari.',
   'В каждой паре сначала ранняя стадия, потом то, что из неё вырастает. В паре «собака — щенок» порядок обратный.',
   'draft'),
  ('v167',
   'category',
   10,
   'Qaysi so''z shu guruhga kiradi?',
   'Tajriba, kuzatish, o''lchash',
   array['taxmin', 'orzu', 'sinov', 'xayol']::text[],
   'Какое слово относится к этой группе?',
   'Эксперимент, наблюдение, измерение',
   array['догадка', 'мечта', 'испытание', 'фантазия']::text[],
   2,
   'Guruhdagilar — haqiqatni amalda tekshirib bilish usullari. Sinov ham shunday; taxmin, orzu va xayol esa faqat fikrda bo''ladi.',
   'В группе — способы узнать правду, проверив её на деле. Испытание тоже; догадка, мечта и фантазия существуют только в мыслях.',
   'draft'),
  ('v169',
   'relation',
   10,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Tajriba — xulosa',
   array['Dalillar — hukm', 'Xulosa — tajriba', 'Olim — tajriba', 'Savol — imtihon']::text[],
   'В какой паре слова связаны так же?',
   'Эксперимент — вывод',
   array['Улики — приговор', 'Вывод — эксперимент', 'Учёный — эксперимент', 'Вопрос — экзамен']::text[],
   0,
   'Xulosa tajribaga, hukm dalillarga asoslanadi: avval asos, keyin undan chiqarilgan qaror. «Xulosa — tajriba»da tartib teskari.',
   'Вывод опирается на эксперимент, приговор — на улики: сначала основание, потом решение. В паре «вывод — эксперимент» порядок обратный.',
   'draft'),
  ('v170',
   'relation',
   10,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Maslahat — buyruq',
   array['Buyruq — maslahat', 'Savol — javob', 'Iltimos — talab', 'Ruxsat — taqiq']::text[],
   'В какой паре слова связаны так же?',
   'Совет — приказ',
   array['Приказ — совет', 'Вопрос — ответ', 'Просьба — требование', 'Разрешение — запрет']::text[],
   2,
   'Maslahatga amal qilish ixtiyoriy, buyruqqa esa majburiy; iltimos va talab ham xuddi shunday: yumshoq va qat''iy shakl.',
   'Совету следовать необязательно, приказу — обязательно; так же различаются просьба и требование: мягкая и жёсткая форма.',
   'draft'),
  ('v171',
   'analogy',
   6,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Chiroq : yorug''lik = karnay : ?',
   array['quloq', 'radio', 'sim', 'tovush']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Лампа : свет = громкоговоритель : ?',
   array['ухо', 'радио', 'провод', 'звук']::text[],
   3,
   'Chiroq yorug''lik, karnay esa tovush chiqaradi: qurilma va u chiqaradigan narsa. Quloq tovushni qabul qiladi, chiqarmaydi.',
   'Лампа испускает свет, громкоговоритель — звук: устройство и то, что оно испускает. Ухо звук воспринимает, а не издаёт.',
   'draft'),
  ('v172',
   'analogy',
   7,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Murabbiy : jamoa = dirijyor : ?',
   array['tayoqcha', 'orkestr', 'kuy', 'sahna']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Тренер : команда = дирижёр : ?',
   array['палочка', 'оркестр', 'мелодия', 'сцена']::text[],
   1,
   'Murabbiy jamoani, dirijyor orkestrni boshqaradi: rahbar va u boshqaradigan odamlar guruhi.',
   'Тренер руководит командой, дирижёр — оркестром: руководитель и группа людей, которой он руководит.',
   'draft'),
  ('v173',
   'analogy',
   8,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Kashfiyot : olim = rekord : ?',
   array['medal', 'stadion', 'sportchi', 'musobaqa']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Открытие : учёный = рекорд : ?',
   array['медаль', 'стадион', 'спортсмен', 'соревнование']::text[],
   2,
   'Kashfiyotni olim, rekordni sportchi qiladi: yutuq va unga erishgan odam. Medal — mukofot, stadion va musobaqa — joy va voqea.',
   'Открытие совершает учёный, рекорд — спортсмен: достижение и тот, кто его добился. Медаль — награда, стадион и соревнование — место и событие.',
   'draft'),
  ('v174',
   'category',
   8,
   'Qaysi so''z shu guruhga kiradi?',
   'Muz, sham, sariyog''',
   array['qog''oz', 'taxta', 'paxta', 'shokolad']::text[],
   'Какое слово относится к этой группе?',
   'Лёд, свеча, сливочное масло',
   array['бумага', 'доска', 'хлопок', 'шоколад']::text[],
   3,
   'Guruhdagilar isitilsa eriydi — qattiqdan suyuqqa aylanadi. Shokolad ham shunday; qog''oz, taxta va paxta esa erimaydi, yonadi.',
   'Всё в группе при нагревании тает — из твёрдого становится жидким. Шоколад тоже; бумага, доска и хлопок не тают, а горят.',
   'draft'),
  ('v175',
   'analogy',
   9,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qo''shish : ayirish = ko''paytirish : ?',
   array['qo''shish', 'bo''lish', 'son', 'natija']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Сложение : вычитание = умножение : ?',
   array['сложение', 'деление', 'число', 'результат']::text[],
   1,
   'Ayirish qo''shishni, bo''lish ko''paytirishni bekor qiladi: amal va unga teskari amal.',
   'Вычитание отменяет сложение, деление — умножение: действие и обратное ему действие.',
   'draft'),
  ('v176',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Qulf : kalit = jumboq : ?',
   array['savol', 'topishmoq', 'o''yin', 'javob']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Замок : ключ = загадка : ?',
   array['вопрос', 'головоломка', 'игра', 'отгадка']::text[],
   3,
   'Kalit qulfni, javob jumboqni «ochadi»: yopiq narsa va uni ochadigan narsa. Topishmoq — jumboqning o''zi, savol ham shunga yaqin.',
   'Ключ открывает замок, отгадка «открывает» загадку: закрытое и то, что его открывает. Головоломка и вопрос — сами похожи на загадку.',
   'draft'),
  ('v177',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Soyabon : ho''l bo''lish = emlash : ?',
   array['davolanish', 'tuzalish', 'kasal bo''lish', 'sog''lom bo''lish']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Зонт : промокнуть = прививка : ?',
   array['лечиться', 'выздороветь', 'заболеть', 'быть здоровым']::text[],
   2,
   'Soyabon ho''l bo''lishdan, emlash kasal bo''lishdan saqlaydi: himoya va u oldini oladigan noxushlik. Sog''lom bo''lish — emlash saqlab qoladigan holat, oldi olinadigan noxushlik emas; davolanish va tuzalish esa kasallikdan keyin keladi.',
   'Зонт защищает от того, чтобы промокнуть, прививка — от того, чтобы заболеть: защита и неприятность, которую она предотвращает. «Быть здоровым» — то, что прививка сохраняет, а не то, что она предотвращает; лечиться и выздороветь — это уже после болезни.',
   'draft'),
  ('v178',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Iqlim : ob-havo = xarakter : ?',
   array['aql', 'odam', 'tarbiya', 'kayfiyat']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Климат : погода = характер : ?',
   array['ум', 'человек', 'воспитание', 'настроение']::text[],
   3,
   'Iqlim — uzoq muddatli barqaror holat, ob-havo — tez o''zgaradigan hozirgi holat. Xarakter ham barqaror, kayfiyat esa tez o''zgaradi.',
   'Климат — долговременное устойчивое состояние, погода — быстро меняющееся текущее. Так же характер устойчив, а настроение быстро меняется.',
   'draft'),
  ('v179',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Sinonim : o''xshashlik = antonim : ?',
   array['so''z', 'qarama-qarshilik', 'lug''at', 'tenglik']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Синоним : сходство = антоним : ?',
   array['слово', 'противоположность', 'словарь', 'равенство']::text[],
   1,
   'Sinonimlar ma''nosining o''xshashligi bilan, antonimlar esa qarama-qarshiligi bilan bog''langan.',
   'Синонимы связаны сходством значений, антонимы — их противоположностью.',
   'draft'),
  ('v180',
   'analogy',
   10,
   'So''roq belgisi o''rniga qaysi so''z mos keladi?',
   'Tovush : sukunat = yorug''lik : ?',
   array['chiroq', 'rang', 'qorong''ilik', 'ko''z']::text[],
   'Какое слово должно стоять вместо знака вопроса?',
   'Звук : тишина = свет : ?',
   array['лампа', 'цвет', 'темнота', 'глаза']::text[],
   2,
   'Sukunat — tovushning yo''qligi, qorong''ilik — yorug''likning yo''qligi: narsa va uning yo''qligi.',
   'Тишина — отсутствие звука, темнота — отсутствие света: явление и его отсутствие.',
   'draft'),
  ('v181',
   'relation',
   10,
   'Qaysi juftlikda so''zlar xuddi shunday bog''langan?',
   'Oqim — to''g''on',
   array['Harakat — tormoz', 'Tormoz — mashina', 'Daryo — suv', 'Tezlik — spidometr']::text[],
   'В какой паре слова связаны так же?',
   'Течение — плотина',
   array['Движение — тормоз', 'Тормоз — машина', 'Река — вода', 'Скорость — спидометр']::text[],
   0,
   'To''g''on oqimni, tormoz harakatni to''xtatadi: jarayon va uni to''xtatadigan narsa. Spidometr tezlikni to''xtatmaydi, faqat o''lchaydi.',
   'Плотина останавливает течение, тормоз — движение: процесс и то, что его останавливает. Спидометр скорость не останавливает, а только измеряет.',
   'draft')
on conflict (key) do update set
  kind = excluded.kind,
  level = excluded.level,
  uz_prompt = excluded.uz_prompt,
  uz_stimulus = excluded.uz_stimulus,
  uz_options = excluded.uz_options,
  ru_prompt = excluded.ru_prompt,
  ru_stimulus = excluded.ru_stimulus,
  ru_options = excluded.ru_options,
  correct = excluded.correct,
  explain_uz = excluded.explain_uz,
  explain_ru = excluded.explain_ru
where v.state = 'draft'
  and v.author_id is null
  and v.updated_by is null
  and (v.kind, v.level, v.uz_prompt, v.uz_stimulus, v.uz_options, v.ru_prompt, v.ru_stimulus, v.ru_options, v.correct, v.explain_uz, v.explain_ru)
      is distinct from
      (excluded.kind, excluded.level, excluded.uz_prompt, excluded.uz_stimulus, excluded.uz_options, excluded.ru_prompt, excluded.ru_stimulus, excluded.ru_options, excluded.correct, excluded.explain_uz, excluded.explain_ru);
